[package]
name = 'real_time_payment'
version = '1.0.0'

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'aptos-cli-v2.0.0'
subdir = 'aptos-move/framework/aptos-framework'

[addresses]
overmind = '0x1337'
admin = '0x1234'